import { createHash } from "node:crypto";
import {
  readdir,
  readFile,
  stat,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

type Manifest = {
  schemaVersion: number;
  sourceRevision: string;
  lessons: Array<{ track: string }>;
  questions: Array<{
    status: string;
    taxonomy: { deckId: string };
  }>;
};

type PackageJson = {
  scripts: Record<string, string>;
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
};

const webRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(webRoot, "..");
const outputPath = path.join(
  repoRoot,
  "docs",
  "ai-context",
  "GENERATED_SNAPSHOT.md",
);
const checkOnly = process.argv.includes("--check");

const manifest = JSON.parse(
  await readFile(
    path.join(webRoot, "src", "generated", "content-manifest.json"),
    "utf8",
  ),
) as Manifest;
const packageJson = JSON.parse(
  await readFile(path.join(webRoot, "package.json"), "utf8"),
) as PackageJson;

const routeFiles = await findFiles(path.join(webRoot, "src", "app"), (file) =>
  /[\\/]route\.ts$/.test(file),
);
const pageFiles = await findFiles(path.join(webRoot, "src", "app"), (file) =>
  /[\\/]page\.tsx$/.test(file),
);
const migrationFiles = await findFiles(
  path.join(webRoot, "supabase", "migrations"),
  (file) => file.endsWith(".sql"),
);
const testFiles = await findFiles(path.join(webRoot, "src"), (file) =>
  file.endsWith(".test.ts") || file.endsWith(".test.tsx"),
);
const sourceFiles = await findFiles(path.join(webRoot, "src"), (file) =>
  /\.(ts|tsx)$/.test(file) && !/\.test\.(ts|tsx)$/.test(file),
);

const fingerprintFiles = (
  await Promise.all([
    collectExistingFiles([
      path.join(repoRoot, "AGENTS.md"),
      path.join(webRoot, "AGENTS.md"),
      path.join(webRoot, ".env.example"),
      path.join(webRoot, "package.json"),
      path.join(webRoot, "package-lock.json"),
    ]),
    findFiles(path.join(repoRoot, ".github", "workflows"), () => true),
    findFiles(path.join(repoRoot, "cpp98_foundation"), isLessonSource),
    findFiles(path.join(repoRoot, "cpp11"), isLessonSource),
    findFiles(path.join(repoRoot, "cpp20"), isLessonSource),
    findFiles(path.join(repoRoot, "python"), isLessonSource),
    findFiles(path.join(repoRoot, "cmake"), isLessonSource),
    findFiles(path.join(webRoot, "content"), (file) =>
      /\.(md|yaml|yml)$/.test(file),
    ),
    findFiles(path.join(webRoot, "scripts"), (file) => file.endsWith(".ts")),
    findFiles(path.join(webRoot, "src"), (file) =>
      /\.(ts|tsx|json)$/.test(file),
    ),
    findFiles(path.join(webRoot, "supabase"), (file) =>
      /\.(sql|toml|md)$/.test(file),
    ),
  ])
).flat();
const fingerprint = await hashFiles(fingerprintFiles);

const tracks = countBy(manifest.lessons, (lesson) => lesson.track);
const statuses = countBy(manifest.questions, (question) => question.status);
const decks = countBy(
  manifest.questions,
  (question) => question.taxonomy.deckId,
);
const latestMigration = migrationFiles
  .map((file) => path.basename(file))
  .sort()
  .at(-1);

const output = `# Generated repository snapshot

> Generated by \`web/scripts/generate-ai-context.ts\`. Do not edit by hand.
> Run \`cd web && npm run context:refresh\`; CI runs \`context:check\`.

## Content

- Manifest schema: ${manifest.schemaVersion}
- Source revision: \`${manifest.sourceRevision}\`
- Lessons: ${manifest.lessons.length} (${formatCounts(tracks)})
- Questions: ${manifest.questions.length} (${formatCounts(statuses)})
- Question decks: ${formatCounts(decks)}

## Application inventory

- App pages: ${pageFiles.length} (${pageFiles.map(appUrl).sort().join(", ")})
- API routes: ${routeFiles.length} (${routeFiles.map(appUrl).sort().join(", ")})
- TypeScript source files excluding tests: ${sourceFiles.length}
- Colocated test files: ${testFiles.length}
- Supabase migrations: ${migrationFiles.length}
- Latest migration filename: \`${latestMigration ?? "none"}\`

## Toolchain declared in package.json

- Next.js: ${packageJson.dependencies.next}
- React: ${packageJson.dependencies.react}
- TypeScript: ${packageJson.devDependencies.typescript}
- Vitest: ${packageJson.devDependencies.vitest}
- OpenAI SDK: ${packageJson.dependencies.openai}
- Supabase JS: ${packageJson.dependencies["@supabase/supabase-js"]}
- Vercel Sandbox: ${packageJson.dependencies["@vercel/sandbox"]}
- npm scripts: ${Object.keys(packageJson.scripts).length}

## Consistency marker

- Project input fingerprint: \`${fingerprint}\`
- Fingerprinted files: ${new Set(fingerprintFiles.map(normalizePath)).size}

The fingerprint covers lesson sources, content files, application source/tests,
scripts, package metadata, environment template, workflows, and Supabase files.
It proves this snapshot was refreshed for the tracked inputs; semantic behavior
changes must still be described in the human-maintained context files.
`;

if (checkOnly) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (normalizeEol(current) !== normalizeEol(output)) {
    console.error(
      "AI context snapshot is stale. Run `npm run context:refresh` from web/ and commit the result.",
    );
    process.exitCode = 1;
  } else {
    console.log("AI context snapshot is current.");
  }
} else {
  await writeFile(outputPath, output, "utf8");
  console.log(
    `Refreshed ${normalizePath(path.relative(repoRoot, outputPath))}.`,
  );
}

async function findFiles(
  root: string,
  include: (file: string) => boolean,
): Promise<string[]> {
  const rootStat = await stat(root).catch(() => null);
  if (!rootStat?.isDirectory()) return [];

  const files: string[] = [];
  const entries = await readdir(root, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await findFiles(fullPath, include)));
    } else if (entry.isFile() && include(fullPath)) {
      files.push(fullPath);
    }
  }
  return files.sort();
}

async function collectExistingFiles(files: string[]) {
  const results = await Promise.all(
    files.map(async (file) => ((await stat(file).catch(() => null)) ? file : null)),
  );
  return results.filter((file): file is string => file !== null);
}

async function hashFiles(files: string[]) {
  const hash = createHash("sha256");
  for (const file of [...new Set(files.map((file) => path.resolve(file)))].sort()) {
    hash.update(normalizePath(path.relative(repoRoot, file)));
    hash.update("\0");
    hash.update(normalizeEol(await readFile(file, "utf8")));
    hash.update("\0");
  }
  return hash.digest("hex");
}

function countBy<T>(items: T[], key: (item: T) => string) {
  const counts = new Map<string, number>();
  for (const item of items) {
    const value = key(item);
    counts.set(value, (counts.get(value) ?? 0) + 1);
  }
  return counts;
}

function formatCounts(counts: Map<string, number>) {
  if (counts.size === 0) return "none";
  return [...counts.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, count]) => `${key}: ${count}`)
    .join(", ");
}

function appUrl(file: string) {
  const relative = normalizePath(
    path.relative(path.join(webRoot, "src", "app"), path.dirname(file)),
  );
  const visible = relative
    .split("/")
    .filter((part) => part && !part.startsWith("("))
    .join("/");
  return `/${visible}`.replace(/\/$/, "") || "/";
}

function isLessonSource(file: string) {
  return (
    file.endsWith("knowledge.md") ||
    file.endsWith("main.cpp") ||
    file.endsWith("main.py") ||
    file.endsWith("CMakeLists.txt")
  );
}

function normalizePath(value: string) {
  return value.replaceAll("\\", "/");
}

function normalizeEol(value: string) {
  return value.replaceAll("\r\n", "\n");
}
