import type { ContentQuestion } from "./schema";

export const questionTypeLabels: Record<ContentQuestion["type"], string> = {
  recall: "Ghi nhớ",
  code_reasoning: "Lập luận về mã",
  pitfall: "Bẫy thường gặp",
  scenario: "Tình huống",
};

export const questionDifficultyLabels: Record<
  ContentQuestion["difficulty"],
  string
> = {
  beginner: "Dễ",
  intermediate: "Trung bình",
  advanced: "Khó",
};

export const questionResponseModeLabels: Record<
  NonNullable<ContentQuestion["responseMode"]>,
  string
> = {
  text: "Text",
  code: "Code",
};

const taxonomyTopicLabels: Record<string, string> = {
  address: "Địa chỉ",
  aggregate: "Kiểu tổng hợp",
  algorithm: "Thuật toán",
  allocation: "Cấp phát bộ nhớ",
  alias: "Tên thay thế",
  aliasing: "Nhiều tên cùng tham chiếu",
  alignment: "Căn chỉnh bộ nhớ",
  assignment: "Phép gán",
  array: "Mảng",
  async: "Tác vụ bất đồng bộ",
  assertion: "Điều kiện kiểm tra",
  atomic: "Thao tác nguyên tử",
  attributes: "Thuộc tính",
  benchmarking: "Đo hiệu năng",
  "binary-parsing": "Phân tích dữ liệu nhị phân",
  bounds: "Giới hạn",
  callable: "Đối tượng có thể gọi",
  capture: "Bắt biến trong lambda",
  cache: "Bộ nhớ đệm",
  chrono: "Thư viện thời gian chrono",
  cpp20: "Tính năng ngôn ngữ C++20",
  "class-design": "Thiết kế lớp",
  "compile-time": "Thời điểm biên dịch",
  constant: "Hằng",
  constraint: "Ràng buộc",
  const: "Tính bất biến",
  constructor: "Hàm tạo",
  container: "Cấu trúc chứa",
  "condition-variable": "Biến điều kiện",
  concurrency: "Lập trình đồng thời",
  conversion: "Chuyển đổi",
  copy: "Sao chép",
  "control-flow": "Luồng điều khiển",
  "data-layout": "Bố trí dữ liệu",
  "data-quality": "Chất lượng dữ liệu",
  "daily-cpp-interview": "Bộ Daily C++ Interview",
  enum: "Kiểu liệt kê",
  "error-handling": "Xử lý lỗi",
  feed: "Nguồn dữ liệu",
  "false-sharing": "Chia sẻ giả",
  final: "Từ khóa final",
  filesystem: "Hệ thống tệp",
  "fixed-point": "Số học dấu phẩy tĩnh",
  "for-each": "Lặp qua từng phần tử",
  foundation: "Nền tảng",
  future: "Kết quả tương lai",
  initialization: "Khởi tạo",
  "interval-statistics": "Thống kê theo khoảng",
  invariants: "Điều bất biến",
  iteration: "Phép lặp",
  iterator: "Bộ lặp",
  lambda: "Biểu thức lambda",
  lambdas: "Biểu thức lambda",
  "language-practice": "Quy tắc ngôn ngữ và thực hành code",
  lifecycle: "Vòng đời hoạt động",
  linkage: "Liên kết tên",
  lifetime: "Vòng đời đối tượng",
  "lock-free": "Không khóa",
  locking: "Khóa đồng bộ",
  lvalue: "Lvalue",
  "market-by-order": "Sổ lệnh theo từng lệnh",
  "market-by-price": "Sổ lệnh theo mức giá",
  "market-data": "Dữ liệu thị trường",
  memory: "Bộ nhớ",
  "memory-model": "Mô hình bộ nhớ",
  "memory-order": "Thứ tự bộ nhớ",
  migration: "Chuyển đổi phiên bản",
  "modern-practices": "Thực hành C++ hiện đại",
  "move-semantics": "Ngữ nghĩa di chuyển",
  mutable: "Từ khóa mutable",
  mutex: "Mutex",
  mutation: "Thay đổi dữ liệu",
  narrowing: "Thu hẹp kiểu",
  namespace: "Không gian tên",
  "node-handle": "Node handle",
  noexcept: "Đặc tả noexcept",
  numeric: "Tính toán số",
  "object-model": "Mô hình đối tượng",
  "object-design": "Thiết kế hướng đối tượng",
  odr: "Quy tắc một định nghĩa",
  optimization: "Tối ưu hóa",
  optional: "Giá trị tùy chọn",
  "order-book": "Sổ lệnh",
  overload: "Nạp chồng",
  override: "Ghi đè",
  ownership: "Quyền sở hữu",
  "parameter-pack": "Gói tham số",
  parallelism: "Xử lý song song",
  parsing: "Phân tích cú pháp",
  performance: "Hiệu năng",
  pointer: "Con trỏ",
  polymorphism: "Đa hình, kế thừa và hàm ảo",
  "pointer-arithmetic": "Số học con trỏ",
  priority: "Mức ưu tiên",
  pmr: "Tài nguyên bộ nhớ đa hình",
  portability: "Tính khả chuyển",
  preprocessing: "Tiền xử lý",
  profiling: "Phân tích hiệu năng",
  queue: "Hàng đợi",
  readability: "Khả năng đọc hiểu",
  recovery: "Khôi phục",
  reference: "Tham chiếu",
  references: "Tham chiếu, move và forwarding",
  scope: "Phạm vi",
  sequencing: "Thứ tự dữ liệu",
  sfinae: "SFINAE",
  sort: "Sắp xếp",
  "smart-pointers": "Smart pointer và ownership",
  "special-members": "Hàm thành viên đặc biệt",
  "special-member-function": "Hàm thành viên đặc biệt",
  static: "Static và khởi tạo",
  stl: "Thư viện chuẩn",
  struct: "Kiểu struct",
  "string-view": "Khung nhìn chuỗi",
  "structured-binding": "Phân rã có cấu trúc",
  templates: "Mẫu",
  "tick-data": "Dữ liệu tick",
  timestamps: "Dấu thời gian",
  toolchain: "Bộ công cụ biên dịch",
  tuple: "Bộ giá trị",
  "type-erasure": "Xóa kiểu",
  "type-deduction": "Suy luận kiểu",
  "type-safety": "An toàn kiểu",
  "type-system": "Hệ thống kiểu",
  "type-traits": "Đặc tính kiểu",
  unicode: "Unicode",
  "value-category": "Phân loại giá trị",
  variables: "Biến",
  variant: "Kiểu hợp an toàn",
  byte: "Byte",
  behavior: "Hành vi chương trình và undefined behavior",
};

export function taxonomyTopicLabel(topic: string) {
  return taxonomyTopicLabels[topic] ?? topic;
}

export function hasTaxonomyTopicLabel(topic: string) {
  return Object.hasOwn(taxonomyTopicLabels, topic);
}
